### ISSUE TITLE
Sorting ignores editor indentation settings

### ISSUE THREAD

**Issue by extratype** [R35007/sort-json-vscode-extension#1]
The extension always uses 2-space indents.

**Comment by R35007** [comment]
I will look into this issue and get back to you.

Thanks,
Siva

**Comment by R35007** [comment]
This issue has been fixed with version 8.0.0. Please take a look :)

**Comment by R35007** [comment]
This issue has been fixed with version 8.0.0. Please take a look :)

**Comment by extratype** [comment]
Thank you very much!!
