### ISSUE TITLE
remove the context menu in output panel

### ISSUE THREAD

**Issue by tjx666** [R35007/sort-json-vscode-extension#10]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/226460902-feb73870-6d5c-4d39-a823-1a849c9cb46e.png">

resolution: https://github.com/gitkraken/vscode-gitlens/commit/7ad3b4677c3a330b93ea7bc10c6d5e2f3e7760ee

**Comment by R35007** [comment]
@tjx666,

I am sorry. I don see a way to remove context for a output panel. I just use `editor/context` in the `package.json` that adds the context also for the output panel. Please feel free to raise a PR if you could provide a solution for this.
