### ISSUE TITLE
validation Extension

### ISSUE THREAD

**Issue by irvnriir** [R35007/sort-json-vscode-extension#12]
i couldn't find linting/validation Extension which would support unquoted keys, but this one can fix such JSON . could you use the parsing from this extension to make a linting one ?

also, when it fixes/sorts such JSON it changes `"` at values to `'` , plz fix that
* with custom sorting being `true` , this:
    
    ```
    {
        name: "",
        name: "",
        value: [
            2,
            1
        ]
    }
    ```
    
* is converted to this:
    
    ```
    {
        name: '',
        value: [
            2,
            1,
        ],
    }
    ```
 
* instead of this:
    
    ```
    {
        name: "",
        value: [
            2,
            1,
        ],
    }
    ```

p.s. "[JSON5 syntax](https://marketplace.visualstudio.com/items?itemName=mrmlnc.vscode-json5)" doesn't work, maybe requires internet connection but that is unacceptable .

**Comment by R35007** [comment]
Hi @irvnriir,

I have fixed the quotes issue. Please check with the version v19.1.0 Sort JSON.

Thanks,
Siva
