### ISSUE TITLE
Maybe it would be possible to register itself as proper formatter?

### ISSUE THREAD

**Issue by mgzenitech** [R35007/sort-json-vscode-extension#14]
Right now this extension provides custom commands, but maybe it would be possible to register as a proper JSON formatter? So that "Format Document" command would work?

```
{
  "json.format.enable": false,
  "[json]": {
    "editor.defaultFormatter": "Thinker.sort-json"
  },
  "[jsonc]": {
    "editor.defaultFormatter": "Thinker.sort-json"
  }
}

```

**Comment by R35007** [comment]
Hi @mgzenitech,

I am sorry I can't make it as a formatter. Bu this extension can format the code by using code actions.

```json
 "editor.codeActionsOnSave": {
    "source.fixAll": "explicit"
  }
```

or you can set a custom key binding to format the code.
```json
{
    "key": "cmd+shift+a",
    "command": "editor.action.codeAction",
    "args": {
        "kind": "source.fixAll.sort-json"
    }
}
```
