### ISSUE TITLE
Can it sort a JS object that reference to other variable?

### ISSUE THREAD

**Issue by dews** [R35007/sort-json-vscode-extension#15]
```
const x = ''
const o = {
  path: [],
  component: x,
  name: 'test'
}
```
Got an error message from VSCode `Invalid JSON. JSON5: invalid character 'x' at 3:14`

**Comment by R35007** [comment]
Hi @dews ,

This extension cannot parse the reference values. Underneath it tries to parse the Json object from the selected string and would throw an error if the selected text is not a valid JSON.
