### ISSUE TITLE
option to ignore arrays on deep sort

### ISSUE THREAD

**Issue by ionut-gheorghe** [R35007/sort-json-vscode-extension#2]
Option to ignore arrays on deep sort

**Comment by R35007** [comment]
Nice option to have. Will try to implement it. Thanks 😊

**Comment by R35007** [comment]
- `sort-json.settings.ignoreArraysOnDeepSort` - If set to true, It ignores Arrays on deep sort. Still sorts the object inside the array. 
- `sort-json.settings.ignoreObjectsOnDeepSort` - If set to true, It ignores Objects on deep sort.

The above feature is added to the version 8.0.0. Please take a look :)
