### ISSUE TITLE
JSON with Comments (jsonc)

### ISSUE THREAD

**Issue by dembeck** [R35007/sort-json-vscode-extension#3]
Microsoft uses JSON with Comments for their configuration files. This allows the use of '//' and '/* */' type comments.

- [Editing JSON with Visual Studio Code](https://code.visualstudio.com/Docs/languages/json#_json-with-comments)

sort-json does not like this, and refuses to sort. It just gives the error "Invalid JSON : Unexpected token '/' at [Line Number] 

Would it be possible to have sort-json ignore the syntax issue and just glue the comment line to the line below them when sorting?

**Comment by R35007** [comment]
I am sorry but it is not possible right now. There isn't any package or any
method to sort JSON having a comments. I will keep this functional trainer
back lock and if there any possible I will let you know. 😊

**Comment by R35007** [comment]
Hi @dembeck ,

With the version [13.0.0](https://marketplace.visualstudio.com/items?itemName=Thinker.sort-json) we can Sort JSON that contains comments in it. 
But for now, the comments will be removed on sorting. I will try to figure out to sort JSON along with comments in feature release.

Thanks,
SIva

**Comment by irvnriir** [comment]
the comments being removed isn't a complete solution

**Comment by R35007** [comment]
Hi @dembeck,

Please take the latest version of Sort JSON. This helps you to sort JSON with comments.

Thanks,
Siva
