### ISSUE TITLE
Sorting is evaluating strings with \u0000 Unicode-escaped sequences

### ISSUE THREAD

**Issue by ZStoner** [R35007/sort-json-vscode-extension#4]
I tried to do a sort on some JSON that contains strings with Unicode-escaped sequences.
**_Note:_** The Unicode-escaped strings weren't part of any "Keys" used for the sort criteria.

#### Issues:
* The resulting sort is physically altering the JSON data by replacing `\u0000` escape sequences with their evaluated Unicode Character.
* _Reference_: Sample JSON data used below was taken from: [GitHub Flavored Markdown Spec: Entity References](https://github.github.com/gfm/#entity-references)
* I tested with some other "Low ASCII" sequences _(...below char 32)_, and those that don't already have a pre-defined escape _(...like `\t`,`\r`,`\n`)_, may also get evaluated into an undesired character.
  * In my case, I tested with `"\u0017"`, and sort converted it to a control symbol that fails JSON parsing.

#### Sample JSON (before Sort):
```json
{
  "&AElig": { "codepoints": [198], "characters": "\u00C6" },
  "&AElig;": { "codepoints": [198], "characters": "\u00C6" },
  "&DownArrow;": { "codepoints": [8595], "characters": "\u2193" },
  "&DownArrowBar;": { "codepoints": [10515], "characters": "\u2913" },
  "&DownTee;": { "codepoints": [8868], "characters": "\u22A4" },
  "&DownTeeArrow;": { "codepoints": [8615], "characters": "\u21A7" },
  "&Downarrow;": { "codepoints": [8659], "characters": "\u21D3" }
}
```

#### Resulting JSON (after Sort Ascending):
```json
{
  "&AElig": {
    "codepoints": [
      198
    ],
    "characters": "Æ"
  },
  "&AElig;": {
    "codepoints": [
      198
    ],
    "characters": "Æ"
  },
  "&DownArrow;": {
    "codepoints": [
      8595
    ],
    "characters": "↓"
  },
  "&Downarrow;": {
    "codepoints": [
      8659
    ],
    "characters": "⇓"
  },
  "&DownArrowBar;": {
    "codepoints": [
      10515
    ],
    "characters": "⤓"
  },
  "&DownTee;": {
    "codepoints": [
      8868
    ],
    "characters": "⊤"
  },
  "&DownTeeArrow;": {
    "codepoints": [
      8615
    ],
    "characters": "↧"
  }
}
```

**Comment by R35007** [comment]
@ZStoner,

Thanks for pointing out this issue. I will try to resolve it in release and will update you :)

**Comment by R35007** [comment]
Hi @ZStoner ,

Since the selected text to sort is converted to JavaScript object all the Unicode will be converted to it's character by default.
To overcome this, I have given a fix which may not work for all the Unicode's.

I have added a new vscode sort setting `sort-json.settings.preserveUnicodeString`. This helps to preserve the Unicode string.
Please use this with caution.

Please update the Sort JSON to [version 15](https://marketplace.visualstudio.com/items?itemName=Thinker.sort-json)
Closing this ticket.

Thanks,
Siva
