### ISSUE TITLE
Feature: orderOverrideKeys by filename

### ISSUE THREAD

**Issue by iliubinskii** [R35007/sort-json-vscode-extension#5]
Hi,

Thank you for great extension.

Can you check this ticket:
https://github.com/microsoft/vscode/issues/172966
in "vscode" repository? They wrote that this is something that should be done on extension level.

So, maybe you can consider a new feature:
Set keys for specific file name (e.g. package.json, composer.json, manifest.json, and so on).
Each of my samples has its own set of keys and it is not convenient to mix them in one list.

**Comment by R35007** [comment]
Hi @ilyub ,

Please update the Extension to version `17.0.1`.
Now we can give the order override keys for a specific file as follows.

```jsonc
{
    "sort-json.settings.orderOverrideKeys": {
      "package.json": ["name", "version"], // order override keys specific to package.json file
      "": ["id", "title"], // order override keys for all files
    }
}
```

Thanks,
Siva

**Comment by iliubinskii** [comment]
Thank you. Just checked. Works as expected.
