### ISSUE TITLE
Allow disabling the "Sorted Successfully" notification

### ISSUE THREAD

**Issue by Gama11** [R35007/sort-json-vscode-extension#7]
Personally I don't find it helpful / it seems like more of a distraction, so an option to turn it off would be nice.

**Comment by R35007** [comment]
@Gama11 

Please update the package to version `16.0.0`
Set `sort-json.settings.showInfoMsg` to `false` to disable Sorted Successfully notification.

Thanks,
Siva

**Comment by Gama11** [comment]
Cool, thanks! 👍
