### ISSUE TITLE
support sort selected json properties

### ISSUE THREAD

**Issue by tjx666** [R35007/sort-json-vscode-extension#8]
My use case is to sort the settings.json. In following screenshot, I only want to sort the selected properties in the red box;

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/226206580-b1efb732-e537-474b-a7c7-392de248d38b.png">

Another same condition is to sort tsconfig.json:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/226206665-98d41011-c901-42dc-aafd-8e664c98b181.png">

**Comment by R35007** [comment]
Hi @tjx666,

I understand your concern, but sorry this is not possible in this extension. This extension is used to sort an object or list. 
The selected string must be a valid JavaScript object.  Just a part of a string cant be sorted.

The alternative way is to use the vscode native `sort lines ascending` and `sort lines descending`.

Thanks,
Siva
