### ISSUE TITLE
can't sort following code

### ISSUE THREAD

**Issue by tjx666** [R35007/sort-json-vscode-extension#9]
```jsonc
{
    // single line comment
    "compilerOptions": /* comment */ {
        "forceConsistentCasingInFileNames": true,
        "skipLibCheck": true
    },
    "a": "111"
}
```

**Comment by R35007** [comment]
Hi @tjx666 ,

I am sorry. I cant able to replicate this issue in my system. It works fine for me. 
Can you please provide the system details along with vscode and node version ?

Thanks,
Siva
